### ISSUE TITLE
Datafrog does not support early termination

### ISSUE THREAD

**Issue by Cypher1** [rust-lang/datafrog#47]
It seems that the following assertions ensure that datafrog will not give partial results.

https://github.com/rust-lang/datafrog/blob/5455139ef26ee36acf229eb8abf45b1dfa453774/src/variable.rs#L307

This is often useful for completeness, but unproductive in real world situations where the are often unbounded numbers solutions to problems and 'good enough' is fine (e.g. estimation, path finding etc.).

Are patches accepted here? I'd like to add an `incomplete` method which would just be the 'complete' method without the assertions, and then replace the body of complete with just the assertions and the result of incomplete.

**Comment by ecstatic-morse** [comment]
@Cypher1 I'm happy to review patches.

The approach you described seems fine. A minor nit, "complete" is a verb in this context, which makes it incompatible with "incomplete".

**Comment by Cypher1** [comment]
Thanks @ecstatic-morse,

That's a helpful nit. Perhaps `report()` or `get_partial()` would be better? Open to suggestions.

I'm having some trouble with the patch. Is it safe to collapse the `.stable` results during running? The Tuples aren't clone by default and I'm not sure how to get all the values 'out' without a clone or returning a temporary (not allowed).

Will have another look at it soon, but I think crepe does a lot of what I'm looking for so I might be better using that. Sorry to suggest / request a feature and then not necessarily contribute.

Cool project either way, thanks for building it

**Comment by Cypher1** [comment]
Thanks, `inspect` might be a better form. I think I might need some hand holding / information about the algorithm used before I can make progress, as I'm getting empty partial results (from `.stable`) until my test problem is fully solved.

Is there a) a canonical algorithm used in datafrog b) an easy [low effort for you] way to bring me up to speed?

**Comment by ecstatic-morse** [comment]
`datafrog` is a bottom-up, semi-naive solver that uses sorted data structures to hold the relations. Notably, `stable` stored as a "leveled", sorted set, where each level is a) sorted and b) twice as big as the previous set (kind of like an in-memory log-structured merge tree).

**Comment by Cypher1** [comment]
I'll read the blog post. I've played with crepe a little but hadn't found DDLog yet.

Thanks @ecstatic-morse for the help!

**Comment by Cypher1** [comment]
Thanks @ecstatic-morse I'm mostly looking for a datalog engine for prototyping, looks like you're right and Crepe is a better fit for now. I'll close this for now but if I come back to datafrog will try to work out how to add this and submit a PR (as 'watching' partial results would be useful for our use case). Cheers
